### ISSUE TITLE
Build RHEL 7.4 stemcell

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh-linux-stemcell-builder#25]
Hi guys

We're trying to build a stemcell based on RHEL 7.4 since some software we use requires at least 7.3. 
However, [this repo's `README` states that it only works with RHEL 7.0, not with RHEL 7.1.](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/585ef9845b07f4d865d2a05498f1cf14cf1d6af5/README.md#special-requirements-for-building-a-rhel-os-image)

The first issue we ran into (newer packages provided by the distro) could be fixed by updating the references in `stemcell_builder/stages/base_rhel/apply.sh` to 
```
    release_package_url="/mnt/rhel/Packages/redhat-release-server-7.4-18.el7.x86_64.rpm"
    epel_package_url="http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm"
```

We fixed the second issue (by default, no `subscription-manager` installed) by installing it using yum in the same script:
```
...
 run_in_chroot $chroot "yum -c /custom_rhel_yum.conf update --assumeyes"
 run_in_chroot $chroot "yum -c /custom_rhel_yum.conf --verbose --assumeyes groupinstall Base"
 run_in_chroot $chroot "yum -c /custom_rhel_yum.conf --verbose --assumeyes groupinstall 'Development Tools'"
+run_in_chroot $chroot "yum -c /custom_rhel_yum.conf --verbose --assumeyes install subscription-manager"
...
```

However, we're now stuck with the following:
```
...
subscription-manager register --username=<removed> --password=<removed>--auto-attach
subscription-manager repos --enable=rhel-7-server-optional-rpms
'
+ disable /mnt/stemcells/null/null/rhel/work/work/chroot/sbin/initctl
+ '[' -e /mnt/stemcells/null/null/rhel/work/work/chroot/sbin/initctl ']'
+ disable /mnt/stemcells/null/null/rhel/work/work/chroot/usr/sbin/invoke-rc.d
+ '[' -e /mnt/stemcells/null/null/rhel/work/work/chroot/usr/sbin/invoke-rc.d ']'
+ unshare -f -p -m /bin/sh
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Error updating system data on the server, see /var/log/rhsm/rhsm.log for more details.
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: <removed>
```

The mentioned file `/var/log/rhsm/rhsm.log` shows the following:
```
2018-01-11 17:28:21,055 [WARNING] subscription-manager:15:MainThread @hwprobe.py:545 - Error with lscpu (/usr/bin/lscpu) subprocess: Command '['/usr/bin/lscpu']' returned non-zero exit status 1
2018-01-11 17:28:24,973 [INFO] subscription-manager:15:MainThread @connection.py:552 - Response: status=200, requestUuid=bb208b66-bc9a-44c8-8120-866eeb40687e, request="GET /subscription/users/<removed>/owners"
2018-01-11 17:28:25,997 [INFO] subscription-manager:15:MainThread @connection.py:552 - Response: status=200, request="GET /subscription/"
2018-01-11 17:28:29,255 [INFO] subscription-manager:15:MainThread @connection.py:552 - Response: status=200, requestUuid=2d3a0863-a1af-48f1-ba2a-71bd0b82ffbd, request="POST /subscription/consumers?owner=<removed>"
2018-01-11 17:28:29,257 [INFO] subscription-manager:15:MainThread @managerlib.py:74 - Consumer created: {'consumer_name': u'<removed>', 'uuid': '<removed>'}
2018-01-11 17:28:29,258 [INFO] subscription-manager:15:MainThread @connection.py:822 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2018-01-11 17:28:30,476 [INFO] subscription-manager:15:MainThread @connection.py:552 - Response: status=200, request="GET /subscription/"
2018-01-11 17:28:32,010 [ERROR] subscription-manager:15:MainThread @utils.py:271 - Error while checking server version: EOF occurred in violation of protocol (_ssl.c:579)
2018-01-11 17:28:32,011 [ERROR] subscription-manager:15:MainThread @utils.py:273 - EOF occurred in violation of protocol (_ssl.c:579)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subscription_manager/utils.py", line 252, in get_server_versions
    status = cp.getStatus()
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 1410, in getStatus
    return self.conn.request_get(method)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 646, in request_get
    return self._request("GET", method, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 672, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 528, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1236, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:579)
2018-01-11 17:28:32,014 [INFO] subscription-manager:15:MainThread @managercli.py:418 - Server Versions: {'rules-version': u'Unknown', 'candlepin': u'Unknown', 'server-type': u'Red Hat Subscription Management'}
2018-01-11 17:28:33,132 [INFO] subscription-manager:15:MainThread @connection.py:552 - Response: status=200, request="GET /subscription/"
2018-01-11 17:28:34,666 [ERROR] subscription-manager:15:MainThread @cache.py:178 - Error updating system data on the server
2018-01-11 17:28:34,666 [ERROR] subscription-manager:15:MainThread @cache.py:179 - EOF occurred in violation of protocol (_ssl.c:579)
```

Can you help us with that? Do you know of anybody who built a RHEL 7.4 stemcell?

**Comment by dpb587-pivotal** [comment]
I'm not aware of others trying to build recent RHEL images, so don't have much advice to offer. Might need to look into some general docs about how they recommend bootstrapping images (outside of BOSH context) to get more insight into their latest recommendations. It may be the case that some of the builder stages need to change significantly.

If you figure anything more out, would be great to hear about it and, even better, a pull request. Feel free to ping if there's more BOSH-specifics that we can help with.

**Comment by MatthiasWinzeler** [comment]
Hi @dpb587-pivotal, thanks for your answer!

I followed up on this; looks like the error above was because I tried to build it on Mac with docker native. If I build it on Ubuntu, I get a step further until it fails:

```
cp: ‘/mnt/stemcells/null/null/rhel/work/work/chroot/usr/share/zoneinfo/UTC’ and ‘/mnt/stemcells/null/null/rhel/work/work/chroot/etc/localtime’ are the same file
```

After I removed the following lines temporarily, the stemcell finally built:
```
# Setting timezone
cp ${chroot}/usr/share/zoneinfo/UTC ${chroot}/etc/localtime
```

However, the specs fail; of the 334 examples, there are 167 failures (will not post the output, since it might contain some RHEL specific stuff I'm not sure I'm allowed to share; happy to do so offline, though). 
This would probably need some in-depth look from someone more familiar with the stemcell building process (to sort out false positives and smaller failures). I'll leave it for now.

**Comment by dpb587-pivotal** [comment]
Sounds like perhaps RHEL is doing some symlinking which affects the copy. May need to use conditional behavior or `cp -f` if it retains the data.

Not sure what the failures were, but yeah, you might need to review the actual failures a bit more closely to distinguish between test intent and OS-specific differences. Feel free to join us in the [cloudfoundry#bosh](https://cloudfoundry.slack.com/messages/C02HPPYQ2/) Slack channel to start discussions about more RHEL-specific failures once you've had a chance to review and classify some of them.

**Comment by MatthiasWinzeler** [comment]
@dpb587-pivotal Thanks - I will check on slack if we decide to really use RHEL.

**Comment by mrosecrance** [comment]
I'm going to close this. It seems stale and it looks like some questions were answered
