### ISSUE TITLE
Error in environment.os_image_rspec_command when running build_os_image target

### ISSUE THREAD

**Issue by dmutreja** [cloudfoundry/bosh-linux-stemcell-builder#9]
Followed the instruction on README to build an Ubuntu trusty image using docker container. 
Ran 
$ bundle exec rake stemcell:build_os_image[ubuntu,trusty,$PWD/tmp/ubuntu_base_image.tgz]

The image builds fine but verification on 

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/Rakefile#L39 

fails with 
````
/opt/bosh/bosh-stemcell/spec/support/spec_assets.rb:11:in `block in <top (required)>': uninitialized constant ShelloutTypes (NameError)
Did you mean?  Shellwords
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
	from /opt/bosh/bosh-stemcell/spec/support/spec_assets.rb:9:in `<top (required)>'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `require'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `block in <top (required)>'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `each'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `<top (required)>'
	from /opt/bosh/bosh-stemcell/spec/os_image/ubuntu_trusty_spec.rb:2:in `require'
	from /opt/bosh/bosh-stemcell/spec/os_image/ubuntu_trusty_spec.rb:2:in `<top (required)>'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /home/ubuntu/.gem/ruby/2.3.1/bin/rspec:22:in `load'
	from /home/ubuntu/.gem/ruby/2.3.1/bin/rspec:22:in `<main>'
````

Running the verification directly from the command line has the same result 

````
ubuntu@73e58c136147:/opt/bosh$ cd /opt/bosh/bosh-stemcell; OS_IMAGE=/opt/bosh/tmp/ubuntu_base_image.tgz bundle exec rspec -fd spec/os_image/ubuntu_trusty_spec.rb
All stemcell_tarball tests are being skipped. STEMCELL_WORKDIR needs to be set
/opt/bosh/bosh-stemcell/spec/support/spec_assets.rb:11:in `block in <top (required)>': uninitialized constant ShelloutTypes (NameError)
Did you mean?  Shellwords
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
	from /opt/bosh/bosh-stemcell/spec/support/spec_assets.rb:9:in `<top (required)>'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `require'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `block in <top (required)>'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `each'
	from /opt/bosh/bosh-stemcell/spec/spec_helper.rb:5:in `<top (required)>'
	from /opt/bosh/bosh-stemcell/spec/os_image/ubuntu_trusty_spec.rb:2:in `require'
	from /opt/bosh/bosh-stemcell/spec/os_image/ubuntu_trusty_spec.rb:2:in `<top (required)>'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/ubuntu/.gem/ruby/2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /home/ubuntu/.gem/ruby/2.3.1/bin/rspec:22:in `load'
	from /home/ubuntu/.gem/ruby/2.3.1/bin/rspec:22:in `<main>'
````

Docker setup in use
````
ubuntu@ubuntu:~$ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
bosh/os-image-stemcell-builder   latest              8674f852b6e4        6 months ago        2.41 GB
ubuntu@ubuntu:~$ docker ps
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS              PORTS               NAMES
73e58c136147        bosh/os-image-stemcell-builder   "/bin/bash"         9 hours ago         Up 9 hours                              friendly_euclid
````

**Comment by f-guichard** [comment]
Hello @dmutreja 

Referenced the same trouble in #8

**Comment by tjvman** [comment]
Wasn't able to reproduce this using current `HEAD` and running the docker container inside a Vagrant box on my OSX machine. `ShelloutTypes` is a fairly recent (last few months) addition, so I'd confirm that you're using a recent version of the repo. The docker image you're using looks correct.

**Comment by zachgersh** [comment]
hey @dmutreja - apologies for the delay but we FINALLY got to the bottom of why this was happening.  Commit to fix it is here:

https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/2d57d60a25c17200ca017ffb929dab2d2ece3b64

Ruby documentation notes that files can be returned in a different order depending on system:

https://ruby-doc.org/core-2.2.0/Dir.html#method-c-glob

**Comment by dmutreja** [comment]
@zachgersh Cool, will pull the commit and check it out.
